# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Randomuser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Randomuser
	pod 'Alamofire'
end

target 'RandomuserTests' do
  inherit! :search_paths
  # Pods for testing
	pod 'Alamofire'
end

target 'RandomuserUITests' do
  # Pods for testing
end


